package com.jeremydyer.core;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.jeremydyer.core.audio.AudioEncoding;
import com.jeremydyer.core.video.Frame;
import com.jeremydyer.core.video.VideoEncoding;

import java.util.List;

/**
 * Represents the Encoding line descriptor from the Dahua generated IDX file that accompanies the .dav files
 * generated by the Dahua 4300S camera.
 *
 * Created by jeremydyer on 3/18/15.
 */
//EncodeFormat={ "Audio" : { "Bitrate" : 64, "Compression" : "G.711A", "Depth" : 16, "Frequency" : 8000,
// "Mode" : 0, "Pack" : "DHAV" },
// "AudioEnable" : true,
// "Video" : { "BitRate" : 4096, "BitRateControl" : "CBR", "Compression" : "H.264", "CustomResolutionName" : "1080P", "FPS" : 20,
// "GOP" : 60, "Height" : 1536, "Pack" : "DHAV", "Profile" : "High", "Quality" : 4, "QualityRange" : 6, "Width" : 2048 },
// "VideoEnable" : true }
public class DahuaIDXEncoding {

    @JsonProperty("AudioEnable")
    private boolean audioEnabled;

    @JsonProperty("Audio")
    private AudioEncoding audioEncoding;

    @JsonProperty("VideoEnable")
    private boolean videoEnabled;

    @JsonProperty("Video")
    private VideoEncoding videoEncoding;

    @JsonIgnore
    private List<Frame> frames;

    //Default constructor to satisfy Jackson ...
    public DahuaIDXEncoding() {}

    public DahuaIDXEncoding(boolean audioEnabled, AudioEncoding audioEncoding, boolean videoEnabled, VideoEncoding videoEncoding, List<Frame> frames) {
        this.audioEnabled = audioEnabled;
        this.audioEncoding = audioEncoding;
        this.videoEnabled = videoEnabled;
        this.videoEncoding = videoEncoding;
        this.frames = frames;
    }

    public boolean isAudioEnabled() {
        return audioEnabled;
    }

    public void setAudioEnabled(boolean audioEnabled) {
        this.audioEnabled = audioEnabled;
    }

    public AudioEncoding getAudioEncoding() {
        return audioEncoding;
    }

    public void setAudioEncoding(AudioEncoding audioEncoding) {
        this.audioEncoding = audioEncoding;
    }

    public boolean isVideoEnabled() {
        return videoEnabled;
    }

    public void setVideoEnabled(boolean videoEnabled) {
        this.videoEnabled = videoEnabled;
    }

    public VideoEncoding getVideoEncoding() {
        return videoEncoding;
    }

    public void setVideoEncoding(VideoEncoding videoEncoding) {
        this.videoEncoding = videoEncoding;
    }

    public List<Frame> getFrames() {
        return frames;
    }

    public void setFrames(List<Frame> frames) {
        this.frames = frames;
    }
}
