package com.jeremydyer.core;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents the Event line descriptor from the Dahua generated IDX file that accompanies the .dav files
 * generated by the Dahua 4300S camera.
 *
 * Created by jeremydyer on 3/13/15.
 */
public class DahuaIDXEvent {

    @JsonProperty("Action")
    private String action;

    @JsonProperty("Index")
    private int index;

    @JsonProperty("Name")
    private String name;

    //Default constructor for Jackson
    public DahuaIDXEvent() {}

    public DahuaIDXEvent(String action, int index, String name) {
        this.action = action;
        this.index = index;
        this.name = name;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public int getIndex() {
        return index;
    }

    public void setIndex(int index) {
        this.index = index;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String toString() {
        return String.format("DahuaIDXEvent[Action: %s, Index: %s, Name: %s]", action,index, name);
    }
}
